<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.tavisca.chatapplication.ServerTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2019-08-19T04:43:51" hostname="RENTLAPT0018" time="0.159">
  <properties/>
  <testcase name="canAcceptMultipleClient()" classname="com.tavisca.chatapplication.ServerTest" time="0.108"/>
  <testcase name="canRespondClient()" classname="com.tavisca.chatapplication.ServerTest" time="0.011"/>
  <testcase name="canRespondWithImages()" classname="com.tavisca.chatapplication.ServerTest" time="0.033"/>
  <testcase name="canAcceptNewClient()" classname="com.tavisca.chatapplication.ServerTest" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[java.net.BindException: Address already in use: NET_Bind
	at java.base/java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:437)
	at java.base/java.net.PlainSocketImpl.bind(PlainSocketImpl.java:174)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:381)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:243)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:135)
	at com.tavisca.chatapplication.Server.<init>(Server.java:14)
	at com.tavisca.chatapplication.ServerTest.lambda$init$0(ServerTest.java:24)
	at java.base/java.lang.Thread.run(Thread.java:844)
Exception in thread "Thread-3" java.lang.NullPointerException
	at com.tavisca.chatapplication.ServerTest.lambda$init$0(ServerTest.java:31)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]></system-err>
</testsuite>
